"""Added2

Revision ID: 387c7206349d
Revises: 3d18f6a5da39
Create Date: 2022-08-27 02:21:19.013736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387c7206349d'
down_revision = '3d18f6a5da39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
