"""Added

Revision ID: 3d18f6a5da39
Revises: cfdf9ccdaa48
Create Date: 2022-08-27 02:20:45.328948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d18f6a5da39'
down_revision = 'cfdf9ccdaa48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
