"""Added3

Revision ID: fb6ef6ae5c83
Revises: 387c7206349d
Create Date: 2022-08-27 02:29:21.014193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6ef6ae5c83'
down_revision = '387c7206349d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('smsinbound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Request_id', sa.String(), nullable=True),
    sa.Column('display_phone', sa.String(), nullable=True),
    sa.Column('phone_no_id', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_wa_id', sa.String(), nullable=True),
    sa.Column('sms_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('text_body', sa.String(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smsinbound_Request_id'), 'smsinbound', ['Request_id'], unique=True)
    op.create_index(op.f('ix_smsinbound_id'), 'smsinbound', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('verifyurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_mode', sa.String(), nullable=True),
    sa.Column('hub_challenge', sa.String(), nullable=True),
    sa.Column('hub_verify_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifyurl_hub_verify_token'), 'verifyurl', ['hub_verify_token'], unique=True)
    op.create_index(op.f('ix_verifyurl_id'), 'verifyurl', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifyurl_id'), table_name='verifyurl')
    op.drop_index(op.f('ix_verifyurl_hub_verify_token'), table_name='verifyurl')
    op.drop_table('verifyurl')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_smsinbound_id'), table_name='smsinbound')
    op.drop_index(op.f('ix_smsinbound_Request_id'), table_name='smsinbound')
    op.drop_table('smsinbound')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
